### PR TITLE
installed Devise

### PR DESCRIPTION
**Pull request by Kwasi008**
Waiting for review for installing devise.

### CODE REVIEW

**Review by jrmcgarvey — CHANGES_REQUESTED** [review]
Kwasi, there are a couple of problems.  You have class Model < ApplicationRecord in model.rb.  That file should not be there.  Similarly you have a devise_for :models entry in routes.rb.  That doesn't belong there either. Am am not sure what happened, because you do not have in db/migrate a *create_models.rb file.  However I think these entries will create problems.  Do you remember the steps you performed to create them?

**Comment by jrmcgarvey** [comment]
Kwasi, it may suffice just to delete model.rb and to remove the devise_for :models line from routes.rb in order to correct the problem.  Make sure you can do a rake db:migrate after you make those changes.

**Comment by Kwasi008** [comment]
Hi John thank you for catching that, I by mistake installed it twice once under the name of model and another time under User, I was able to deleted and make all the changes asked, please let me know what you think

**Review by jrmcgarvey — APPROVED** [review]
OK, looks good now

**Pull request merged**
