### PR TITLE
Volunteer model

### PR DESCRIPTION
**Pull request by Tilneil**
Hi John,

Attached is the volunteer model. I already started the volunteer controller here as well. I got the index and the new forms to work, but they're not saving any data. When I did the inspect feature, it shows that the submit button is disabled from submitting data. Is this on purpose to prevent us from saving things to the database? If not, do you know how I could correct it? I found this code online https://stackoverflow.com/questions/42016113/rails-data-disable-with-re-enabling-button but when I run rails it get an error message (perhaps I'm doing it incorrectly?). 

I also commented out sections that references the other tables. 

For the Volunteers controller, I'm trying to figure out how to access the homes. Maybe we can discuss on our call tomorrow? I want to have the volunteer be able to see homes needing repairs based on the repairs they select for their profile as their skills. So if some says they have skills in painting, they will see all homeowners that need volunteers to paint. 

I'm going to look at your appointment app to see if I can figure out something. 

Let me know if you have any questions or suggestions in the meantime. 

Tilneil

### CODE REVIEW

**Review by jrmcgarvey — COMMENTED** [review]
Tilneil, you have a conflict in schema.rb that would have to be resolved before merge.  I can show you how to do this, but I suggest that we will want to wait until Kwasi drops his latest change, which will also affect schema.rb.  The resolution involves a git rebase operation.  In general the files look good, except I don't know why there are 53 of them that changed.  We should discuss.  Also, user_id needs to be identified as a foreign key.

**Comment by jrmcgarvey** [comment]
Also Tilneil, we need to make sure that your stuff is all working before it is integrated.  That is, we need to understand why the submit is failing or disabled.  Also, I don't think that we will want all volunteers to see all the information about the homes, such as the homeowner name.  That would effectively publish the name of the requesting homeowner to anyone wanting to see it.  We may want to disclose the zipcode so that the volunteer can figure out about where they would be working.  Then an administrator would connect them with the homeowner.

**Review by jrmcgarvey — CHANGES_REQUESTED** [review]
See previous comments

**Comment by Tilneil** [comment]
Hi John,

I did run a rubocop and did an autocorrect and auto format. It changed a lot of the rails generated files. 

I also had a hard time creating a model at first, so I kept deleting and cloning the repository thinking I did something wrong. Realize I had to generate rails first after going to back to review my notes. Not sure if that caused a problem. 

Do you think I should I try writing the form in normal html instead of using the form helpers? 

Or is it best practice to use form helpers? 

Thanks John,

Tilneil

**Pull request closed without merging**
